"""Add first name and surname

Revision ID: a16d3661a3e1
Revises: 0f04fcd125d2
Create Date: 2026-08-02 22:55:28.136803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16d3661a3e1'
down_revision: Union[str, Sequence[str], None] = '0f04fcd125d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(), nullable=True))
    op.drop_index(op.f('ix_userdegreegroup_degree_group_id'), table_name='userdegreegroup')
    op.drop_index(op.f('ix_userdegreegroup_user_id'), table_name='userdegreegroup')
    op.drop_table('userdegreegroup')
    op.drop_index(op.f('ix_degreegroup_name'), table_name='degreegroup')
    op.drop_table('degreegroup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'first_name')
    op.create_table('degreegroup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('degreegroup_pkey'))
    )
    op.create_index(op.f('ix_degreegroup_name'), 'degreegroup', ['name'], unique=True)
    op.create_table('userdegreegroup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('degree_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['degree_group_id'], ['degreegroup.id'], name=op.f('userdegreegroup_degree_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('userdegreegroup_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userdegreegroup_pkey'))
    )
    op.create_index(op.f('ix_userdegreegroup_user_id'), 'userdegreegroup', ['user_id'], unique=False)
    op.create_index(op.f('ix_userdegreegroup_degree_group_id'), 'userdegreegroup', ['degree_group_id'], unique=False)
    # ### end Alembic commands ###
