"""add topic prev next links

Revision ID: db775bf8f855
Revises: c4d4a62c44dc
Create Date: 2026-06-13 20:49:35.677224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db775bf8f855'
down_revision: Union[str, Sequence[str], None] = 'c4d4a62c44dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('prev_id', sa.Integer(), nullable=True))
    op.add_column('topic', sa.Column('next_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_topic_next_id'), 'topic', ['next_id'], unique=False)
    op.create_index(op.f('ix_topic_prev_id'), 'topic', ['prev_id'], unique=False)
    op.create_foreign_key(None, 'topic', 'topic', ['next_id'], ['id'])
    op.create_foreign_key(None, 'topic', 'topic', ['prev_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_index(op.f('ix_topic_prev_id'), table_name='topic')
    op.drop_index(op.f('ix_topic_next_id'), table_name='topic')
    op.drop_column('topic', 'next_id')
    op.drop_column('topic', 'prev_id')
    # ### end Alembic commands ###
